# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.account')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.journal')),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('ledger_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.account')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.ledger'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='trans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.transaction'),
        ),
    ]
